apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8lfn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0069-tenant/tkrw-pr712-0075-0069-app/devfile-sample-8lfn@sha256:de30fc316087e2961e367240bddb149651ea2b96b5a9143969f5b22fd2f96689
        name: my-nodejs
        resources: {}
status: {}
